import { chromium } from '@playwright/test';
const BASE='http://localhost:5190';
const b=await chromium.launch({headless:true});
const p=await (await b.newContext({viewport:{width:1400,height:950}})).newPage();
p.on('pageerror',e=>console.log('[pageerror]',String(e).slice(0,400)));
p.on('console',m=>{ if(m.type()==='error') console.log('[err]',m.text().slice(0,300)); });
await p.goto(`${BASE}/login`);
await p.locator('input[type=email]').fill('lecture-verify@folio.local');
await p.locator('input[type=password]').fill('lecture-verify-pw-123');
await p.getByRole('button',{name:/sign in|log in/i}).click();
await p.waitForURL(u=>!u.pathname.includes('/login'),{timeout:20000});
await p.waitForTimeout(2500);
console.log('URL:',p.url());
console.log('BODY TEXT:', (await p.locator('body').innerText()).slice(0,600).replace(/\n+/g,' | '));
console.log('buttons:', (await p.getByRole('button').allTextContents()).slice(0,30).join(' / '));
await p.screenshot({path:'C:/Users/sampo/AppData/Local/Temp/claude/C--Users-sampo/849eae65-28d8-4225-b546-2291d181cb4f/scratchpad/dbg.png'});
await b.close();
