import { chromium } from '@playwright/test';
const BASE='http://localhost:5190';
const b=await chromium.launch({headless:true});
const p=await (await b.newContext({viewport:{width:1400,height:950}})).newPage();
p.on('pageerror',e=>console.log('[pageerror]',String(e).slice(0,500)));
await p.goto(`${BASE}/login`);
await p.locator('input[type=email]').fill('lecture-verify@folio.local');
await p.locator('input[type=password]').fill('lecture-verify-pw-123');
await p.getByRole('button',{name:/sign in|log in/i}).click();
await p.waitForURL(u=>!u.pathname.includes('/login'),{timeout:20000});
await p.waitForTimeout(1500);
await p.keyboard.press('Control+p');
await p.waitForTimeout(800);
console.log('after ctrl+p, palette visible:', await p.getByPlaceholder('Type a command…').count());
await p.getByPlaceholder('Type a command…').fill('Import slides');
await p.waitForTimeout(800);
console.log('results:', (await p.locator('[role=option], .cp-item, li').allTextContents()).slice(0,10).join(' | '));
await p.keyboard.press('Enter');
await p.waitForTimeout(2000);
console.log('BODY:', (await p.locator('body').innerText()).slice(0,900).replace(/\n+/g,' | '));
console.log('tabs:', (await p.getByRole('tab').allTextContents()).join(' / '));
await p.screenshot({path:'C:/Users/sampo/AppData/Local/Temp/claude/C--Users-sampo/849eae65-28d8-4225-b546-2291d181cb4f/scratchpad/dbg2.png'});
await b.close();
