// Codegen: turn the Material Symbols Rounded SVGs we actually use into one small
// TypeScript module of path data.
//
// Why codegen and not the icon font the design links: the app's CSP pins
// `font-src 'self' data:` and `style-src 'self' 'unsafe-inline'`, so
// fonts.googleapis.com is refused outright (server/src/lib/csp.ts, and
// server/test/csp.test.ts guards it). Self-hosting the font instead would ship a
// multi-megabyte woff2 to every visitor for ~60 glyphs. This emits only the glyphs
// named below, so @material-symbols/svg-300 stays a devDependency and nothing extra
// reaches the browser.
//
// Weight 300 and the non-filled variant are deliberate: they are what the design
// specifies (`opsz,wght,FILL,GRAD@20..48,300,0,0`).
//
// Run: npm run gen:icons -w web
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const SVG_DIR = resolve(here, '../../node_modules/@material-symbols/svg-300/rounded');
const OUT = resolve(here, '../src/components/iconPaths.ts');

// app icon name -> Material Symbols Rounded glyph name
const MAP = {
  'chevron-left': 'chevron_left',
  'chevron-right': 'chevron_right',
  'chevron-down': 'keyboard_arrow_down',
  x: 'close',
  check: 'check',
  plus: 'add',
  search: 'search',
  menu: 'menu',
  more: 'more_horiz',
  trash: 'delete',
  archive: 'archive',
  unarchive: 'unarchive',
  pencil: 'edit',
  sun: 'light_mode',
  moon: 'dark_mode',
  home: 'home',
  layers: 'layers',
  sparkles: 'star_shine',
  upload: 'upload',
  copy: 'content_copy',
  move: 'drive_file_move',
  refresh: 'refresh',
  pin: 'keep',
  'pin-filled': 'keep',
  'alert-circle': 'error',
  info: 'info',
  'folder-plus': 'create_new_folder',
  gem: 'diamond',
  blocks: 'widgets',
  cloud: 'cloud',
  phone: 'mobile',
  palette: 'palette',
  camera: 'photo_camera',
  'file-text': 'description',
  download: 'download',
  'rotate-ccw': 'history',
  link: 'link',
  'sparkles-off': 'block',
  lock: 'lock',
  'log-out': 'logout',
  smile: 'mood',
  canvas: 'dashboard',
  cursor: 'arrow_selector_tool',
  hand: 'back_hand',
  sticky: 'sticky_note_2',
  type: 'text_fields',
  image: 'image',
  square: 'crop_square',
  circle: 'circle',
  'arrow-right': 'arrow_forward',
  pen: 'draw',
  highlighter: 'ink_highlighter',
  eraser: 'ink_eraser',
  undo: 'undo',
  redo: 'redo',
  maximize: 'fullscreen',
  'bring-front': 'flip_to_front',
  'send-back': 'flip_to_back',

  // ---- chrome introduced by the dark-chrome redesign ----
  'manage-search': 'manage_search',
  'note-add': 'note_add',
  tag: 'tag',
  share: 'ios_share',
  slideshow: 'slideshow',
  columns: 'view_column_2',
  minus: 'remove',
  'header-footer': 'vertical_split',
  'format-clear': 'format_clear',
  'list-bulleted': 'format_list_bulleted',
  'list-numbered': 'format_list_numbered',
  checklist: 'checklist',
  'indent-less': 'format_indent_decrease',
  'indent-more': 'format_indent_increase',
  'align-left': 'format_align_left',
  'align-center': 'format_align_center',
  'align-right': 'format_align_right',
  'align-justify': 'format_align_justify',
  'line-spacing': 'format_line_spacing',
};

const missing = [];
const entries = [];

for (const [appName, glyph] of Object.entries(MAP)) {
  const file = resolve(SVG_DIR, `${glyph}.svg`);
  if (!existsSync(file)) {
    missing.push(`${appName} -> ${glyph}`);
    continue;
  }
  const svg = readFileSync(file, 'utf8');
  // Every Material Symbol is a single <path d="..."/> on a 0 -960 960 960 viewBox.
  const matches = [...svg.matchAll(/<path[^>]*\sd="([^"]+)"/g)].map((m) => m[1]);
  if (matches.length === 0) {
    missing.push(`${appName} -> ${glyph} (no path data)`);
    continue;
  }
  entries.push([appName, matches.join(' ')]);
}

if (missing.length) {
  console.error('Unresolved Material Symbols:\n  ' + missing.join('\n  '));
  process.exit(1);
}

const body = entries.map(([n, d]) => `  ${JSON.stringify(n)}: ${JSON.stringify(d)},`).join('\n');

writeFileSync(
  OUT,
  `// GENERATED by scripts/gen-icons.mjs - do not edit by hand.
// Material Symbols Rounded, weight 300, FILL 0. Run \`npm run gen:icons -w web\`
// after changing the map in that script.
//
// All glyphs share the Material Symbols viewBox, which is NOT the 24x24 box the old
// hand-rolled set used - Icon.tsx sets it, so nothing else needs to know.
export const ICON_VIEWBOX = '0 -960 960 960';

export const ICON_PATHS = {
${body}
} as const;

export type IconName = keyof typeof ICON_PATHS;
`,
  'utf8',
);

console.log(`Wrote ${entries.length} icons to ${OUT}`);
